# Generated by Django 2.2.6 on 2019-12-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
